# Use the official Jenkins agent image as the base
FROM jenkins/agent:latest

# Switch to root to install Go and other dependencies
USER root

# Set environment variables for Go
ENV GO_VERSION=1.20.6
ENV GOPATH=/go
ENV PATH=$PATH:/usr/local/go/bin:$GOPATH/bin:/usr/local/bin
ENV GO111MODULE=on

# Install Go
RUN curl -fsSL https://golang.org/dl/go${GO_VERSION}.linux-amd64.tar.gz | tar -C /usr/local -xz && \
    mkdir -p $GOPATH/src $GOPATH/bin $GOPATH/pkg && \
    chmod -R 777 $GOPATH

# Install required packages and golangci-lint
RUN apt-get update && \
    apt-get install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg2 \
    software-properties-common \
    lsb-release \
    python3 \
    python3-pip && \
    curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b /usr/local/bin && \
    curl -fsSL https://download.docker.com/linux/debian/gpg | apt-key add - && \
    curl -sSL https://github.com/golang-migrate/migrate/releases/download/v4.15.0/migrate.linux-amd64.tar.gz | tar -xz -C /usr/local/bin && \
    echo "deb [arch=amd64] https://download.docker.com/linux/debian bullseye stable" > /etc/apt/sources.list.d/docker.list && \
    apt-get update && \
    apt-get -y install docker-ce-cli && \
    apt-get update && apt-get install -y \
    docker.io && \
    rm -rf /var/lib/apt/lists/*

# Ensure Jenkins user has permission to access Docker (docker group setup)
RUN groupadd -f docker && usermod -aG docker jenkins

# Ensure Jenkins user has access to Go binaries
RUN echo "export PATH=$PATH:/usr/local/bin" >> /home/jenkins/.bashrc

# Verify golangci-lint installation
RUN ls -l /usr/local/bin | grep golangci-lint && \
    chmod +x /usr/local/bin/golangci-lint && \
    golangci-lint --version

# Check Python and PIP versions (optional)
RUN python3 --version && pip3 --version

# Verify the installation
RUN migrate -version
# Verify Go installation
RUN /usr/local/go/bin/go version

# Switch back to Jenkins user
USER jenkins
WORKDIR /home/jenkins
